//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.30 at 12:36:08 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3.org/2005/sparql-results#")
package eu.granatum.xsd;
